### PR TITLE
Lossily compress all LL graphics through use of `spritter optimize . -r --lossy`

### PR DESCRIPTION
**Pull request by notnotmelon**
This PR applies lossy compression to every .png in Lunar Landings.
This is the same compression as used in Maraxsis and Pyanodons.

This PR reduces the bundle size by exactly 20MB (-25%)

Here is the full spritter log:

```
C:\Users\zacha\Documents\factorio\1.2\mods\LunarLandings>spritter optimize . -r --lossy
2024-12-20T04:24:48.492Z INFO  spritter > spritter v1.2.0
2024-12-20T04:24:48.557Z INFO  spritter > found 147 images after searching through 138 folders
2024-12-20T04:24:48.836Z INFO  spritter > .\graphics\ice.png: -69.70% smaller, saved 164.33kB
2024-12-20T04:24:48.870Z INFO  spritter > .\graphics\landing-pad.png: -61.76% smaller, saved 6.33kB
2024-12-20T04:24:48.909Z INFO  spritter > .\graphics\silica.png: -63.65% smaller, saved 6.57kB
2024-12-20T04:24:48.948Z INFO  spritter > .\graphics\silicon.png: -67.40% smaller, saved 9.69kB
2024-12-20T04:24:51.058Z INFO  spritter > .\graphics\cliffs\cliff-entrance.png: -63.60% smaller, saved 388.83kB
2024-12-20T04:24:56.693Z INFO  spritter > .\graphics\cliffs\cliff-inner.png: -62.25% smaller, saved 868.49kB
2024-12-20T04:25:02.659Z INFO  spritter > .\graphics\cliffs\cliff-outer.png: -61.88% smaller, saved 977.81kB
2024-12-20T04:25:07.692Z INFO  spritter > .\graphics\cliffs\cliff-sides.png: -61.51% smaller, saved 1.16MB
2024-12-20T04:25:08.346Z INFO  spritter > .\graphics\entities\computer-core.png: -71.03% smaller, saved 256.11kB
2024-12-20T04:25:31.604Z INFO  spritter > .\graphics\entities\computer-core_animation.png: -72.89% smaller, saved 4.79MB
2024-12-20T04:25:31.722Z INFO  spritter > .\graphics\entities\mass-driver-requester.png: -70.83% smaller, saved 55.92kB
2024-12-20T04:25:32.110Z INFO  spritter > .\graphics\entities\mass-driver.png: -73.68% smaller, saved 82.67kB
2024-12-20T04:25:32.370Z INFO  spritter > .\graphics\entities\rtg-shadow.png: -34.48% smaller, saved 2.28kB
2024-12-20T04:25:32.608Z INFO  spritter > .\graphics\entities\rtg.png: -72.99% smaller, saved 77.04kB
2024-12-20T04:25:32.662Z INFO  spritter > .\graphics\fluid\astroflux.png: -72.34% smaller, saved 7.61kB
2024-12-20T04:25:32.700Z INFO  spritter > .\graphics\fluid\helium-3.png: -81.16% smaller, saved 12.22kB
2024-12-20T04:25:32.741Z INFO  spritter > .\graphics\fluid\oxygen.png: -80.82% smaller, saved 11.46kB
2024-12-20T04:25:32.790Z INFO  spritter > .\graphics\icons\alumina.png: -60.70% smaller, saved 5.60kB
2024-12-20T04:25:32.831Z INFO  spritter > .\graphics\icons\aluminium-ore-2.png: -62.12% smaller, saved 7.55kB
2024-12-20T04:25:32.877Z INFO  spritter > .\graphics\icons\aluminium-ore-3.png: -62.56% smaller, saved 8.10kB
2024-12-20T04:25:32.929Z INFO  spritter > .\graphics\icons\aluminium-ore-4.png: -61.94% smaller, saved 7.72kB
2024-12-20T04:25:32.976Z INFO  spritter > .\graphics\icons\aluminium-ore.png: -65.18% smaller, saved 8.16kB
2024-12-20T04:25:33.042Z INFO  spritter > .\graphics\icons\aluminium-plate.png: -57.57% smaller, saved 8.76kB
2024-12-20T04:25:33.095Z INFO  spritter > .\graphics\icons\arc-furnace.png: -64.57% smaller, saved 8.31kB
2024-12-20T04:25:33.166Z INFO  spritter > .\graphics\icons\arrow.png: -58.55% smaller, saved 2.62kB
2024-12-20T04:25:33.192Z INFO  spritter > .\graphics\icons\background.png: -93.40% smaller, saved 1.82kB
2024-12-20T04:25:33.235Z INFO  spritter > .\graphics\icons\computer-core.png: -69.04% smaller, saved 8.20kB
2024-12-20T04:25:33.273Z INFO  spritter > .\graphics\icons\condense-steam.png: -61.94% smaller, saved 4.85kB
2024-12-20T04:25:33.321Z INFO  spritter > .\graphics\icons\core-extractor.png: -66.19% smaller, saved 9.37kB
2024-12-20T04:25:33.375Z INFO  spritter > .\graphics\icons\fusion-fuel.png: -68.06% smaller, saved 8.27kB
2024-12-20T04:25:33.420Z INFO  spritter > .\graphics\icons\heat-furnace.png: -65.23% smaller, saved 6.60kB
2024-12-20T04:25:33.477Z INFO  spritter > .\graphics\icons\ice-2.png: -61.56% smaller, saved 7.37kB
2024-12-20T04:25:33.532Z INFO  spritter > .\graphics\icons\ice-3.png: -61.95% smaller, saved 7.41kB
2024-12-20T04:25:33.588Z INFO  spritter > .\graphics\icons\ice.png: -62.68% smaller, saved 7.57kB
2024-12-20T04:25:33.639Z INFO  spritter > .\graphics\icons\low-gravity-assembling-machine.png: -64.56% smaller, saved 8.15kB
2024-12-20T04:25:34.236Z INFO  spritter > .\graphics\icons\luna-large.png: -14.73% smaller, saved 19.11kB
2024-12-20T04:25:34.271Z INFO  spritter > .\graphics\icons\luna.png: -45.10% smaller, saved 2.93kB
2024-12-20T04:25:34.310Z INFO  spritter > .\graphics\icons\mass-driver-requester.png: -59.23% smaller, saved 5.71kB
2024-12-20T04:25:34.350Z INFO  spritter > .\graphics\icons\melt-ice.png: -64.14% smaller, saved 5.07kB
2024-12-20T04:25:34.393Z INFO  spritter > .\graphics\icons\moon-rock-1.png: -61.09% smaller, saved 6.67kB
2024-12-20T04:25:34.437Z INFO  spritter > .\graphics\icons\moon-rock-2.png: -61.40% smaller, saved 7.10kB
2024-12-20T04:25:34.479Z INFO  spritter > .\graphics\icons\moon-rock-3.png: -60.82% smaller, saved 7.19kB
2024-12-20T04:25:34.518Z INFO  spritter > .\graphics\icons\moon-rock.png: -60.68% smaller, saved 7.01kB
2024-12-20T04:25:34.530Z INFO  spritter > .\graphics\icons\moon.png: -52.13% smaller, saved 1.22kB
2024-12-20T04:25:35.421Z INFO  spritter > .\graphics\icons\nauvis.png: -77.43% smaller, saved 343.56kB
2024-12-20T04:25:35.449Z INFO  spritter > .\graphics\icons\oxygen-diffuser.png: -1.47% smaller, saved 77B
2024-12-20T04:25:35.503Z INFO  spritter > .\graphics\icons\quantum-module.png: -68.58% smaller, saved 10.96kB
2024-12-20T04:25:35.539Z INFO  spritter > .\graphics\icons\quantum-processor.png: -56.01% smaller, saved 3.78kB
2024-12-20T04:25:35.583Z INFO  spritter > .\graphics\icons\quantum-science-pack.png: -66.77% smaller, saved 7.09kB
2024-12-20T04:25:35.616Z INFO  spritter > .\graphics\icons\recycle.png: -48.66% smaller, saved 2.39kB
2024-12-20T04:25:35.663Z INFO  spritter > .\graphics\icons\red-mud.png: -58.36% smaller, saved 4.76kB
2024-12-20T04:25:35.703Z INFO  spritter > .\graphics\icons\rich-moon-rock-1.png: -47.16% smaller, saved 4.11kB
2024-12-20T04:25:35.742Z INFO  spritter > .\graphics\icons\rich-moon-rock-2.png: -49.85% smaller, saved 4.25kB
2024-12-20T04:25:35.783Z INFO  spritter > .\graphics\icons\rich-moon-rock-3.png: -47.45% smaller, saved 4.24kB
2024-12-20T04:25:35.829Z INFO  spritter > .\graphics\icons\rich-moon-rock.png: -49.93% smaller, saved 4.56kB
2024-12-20T04:25:35.875Z INFO  spritter > .\graphics\icons\rocket-control-unit.png: -61.99% smaller, saved 6.91kB
2024-12-20T04:25:35.908Z INFO  spritter > .\graphics\icons\rtg-depleted.png: -23.44% smaller, saved 489B
2024-12-20T04:25:35.947Z INFO  spritter > .\graphics\icons\rtg.png: -84.31% smaller, saved 17.90kB
2024-12-20T04:25:35.991Z INFO  spritter > .\graphics\icons\space-science-pack.png: -66.91% smaller, saved 7.13kB
2024-12-20T04:25:36.029Z INFO  spritter > .\graphics\icons\steam-condenser.png: -63.81% smaller, saved 5.12kB
2024-12-20T04:25:36.103Z INFO  spritter > .\graphics\item\interstellar-satellite-light.png: -19.89% smaller, saved 491B
2024-12-20T04:25:36.155Z INFO  spritter > .\graphics\item\interstellar-satellite.png: -63.80% smaller, saved 7.16kB
2024-12-20T04:25:37.987Z INFO  spritter > .\graphics\moon-rock\moon-rock.png: -73.55% smaller, saved 1.06MB
2024-12-20T04:25:39.805Z INFO  spritter > .\graphics\moon-rock\rich-moon-rock.png: -87.34% smaller, saved 2.79MB
2024-12-20T04:25:40.733Z INFO  spritter > .\graphics\oxygen-diffuser\beacon-antenna-shadow.png: could not optimize further
2024-12-20T04:25:41.370Z INFO  spritter > .\graphics\oxygen-diffuser\beacon-antenna.png: -5.37% smaller, saved 7.71kB
2024-12-20T04:25:41.468Z INFO  spritter > .\graphics\oxygen-diffuser\beacon-base-shadow.png: could not optimize further
2024-12-20T04:25:41.561Z INFO  spritter > .\graphics\oxygen-diffuser\beacon-base.png: -3.56% smaller, saved 857B
2024-12-20T04:25:41.575Z INFO  spritter > .\graphics\oxygen-diffuser\beacon-reflection.png: -4.08% smaller, saved 28B
2024-12-20T04:25:42.219Z INFO  spritter > .\graphics\pipe-covers\big_east_covers.png: -73.11% smaller, saved 11.74kB
2024-12-20T04:25:42.897Z INFO  spritter > .\graphics\pipe-covers\big_south_covers.png: -93.51% smaller, saved 192.01kB
2024-12-20T04:25:43.561Z INFO  spritter > .\graphics\pipe-covers\big_west_covers.png: -73.78% smaller, saved 15.70kB
2024-12-20T04:25:44.253Z INFO  spritter > .\graphics\pipe-covers\data_south_covers.png: -69.24% smaller, saved 24.98kB
2024-12-20T04:25:44.305Z INFO  spritter > .\graphics\pipe-covers\east_covers.png: -84.32% smaller, saved 10.69kB
2024-12-20T04:25:44.332Z INFO  spritter > .\graphics\pipe-covers\east_covers_insulated.png: -87.13% smaller, saved 7.39kB
2024-12-20T04:25:45.124Z INFO  spritter > .\graphics\pipe-covers\electricity_south_covers.png: -65.84% smaller, saved 50.40kB
2024-12-20T04:25:45.141Z INFO  spritter > .\graphics\pipe-covers\north_basic_covers.png: could not optimize further
2024-12-20T04:25:45.170Z INFO  spritter > .\graphics\pipe-covers\north_long_basic_covers.png: -50.55% smaller, saved 2.31kB
2024-12-20T04:25:45.185Z INFO  spritter > .\graphics\pipe-covers\south_basic_covers.png: -11.25% smaller, saved 303B
2024-12-20T04:25:45.215Z INFO  spritter > .\graphics\pipe-covers\south_basic_covers_data.png: -43.93% smaller, saved 1.54kB
2024-12-20T04:25:45.228Z INFO  spritter > .\graphics\pipe-covers\south_basic_covers_insulated.png: -92.48% smaller, saved 11.44kB
2024-12-20T04:25:45.280Z INFO  spritter > .\graphics\pipe-covers\south_pumpjack_covers.png: -63.22% smaller, saved 7.30kB
2024-12-20T04:25:45.972Z INFO  spritter > .\graphics\pipe-covers\steam_south_covers.png: -70.70% smaller, saved 57.41kB
2024-12-20T04:25:46.006Z INFO  spritter > .\graphics\pipe-covers\west_covers.png: -85.90% smaller, saved 11.56kB
2024-12-20T04:25:46.032Z INFO  spritter > .\graphics\pipe-covers\west_covers_insulated.png: -87.58% smaller, saved 7.63kB
2024-12-20T04:25:46.147Z INFO  spritter > .\graphics\remote-drone\compilatron-corpse-mask.png: -73.89% smaller, saved 16.02kB
2024-12-20T04:25:46.277Z INFO  spritter > .\graphics\remote-drone\compilatron-corpse.png: -73.80% smaller, saved 49.02kB
2024-12-20T04:25:46.316Z INFO  spritter > .\graphics\remote-drone\compilatron-icon.png: -57.70% smaller, saved 3.68kB
2024-12-20T04:25:46.581Z INFO  spritter > .\graphics\remote-drone\compilatron-walk-1-mask.png: -51.97% smaller, saved 45.06kB
2024-12-20T04:25:47.112Z INFO  spritter > .\graphics\remote-drone\compilatron-walk-1.png: -70.59% smaller, saved 293.02kB
2024-12-20T04:25:47.399Z INFO  spritter > .\graphics\remote-drone\compilatron-walk-2-mask.png: -52.45% smaller, saved 45.54kB
2024-12-20T04:25:47.919Z INFO  spritter > .\graphics\remote-drone\compilatron-walk-2.png: -69.51% smaller, saved 287.52kB
2024-12-20T04:25:48.663Z INFO  spritter > .\graphics\remote-drone\compilatron-walk-shadow.png: -0.81% smaller, saved 245B
2024-12-20T04:25:48.740Z INFO  spritter > .\graphics\remote-drone\corpse-icon.png: -81.26% smaller, saved 41.74kB
2024-12-20T04:25:48.773Z INFO  spritter > .\graphics\remote-drone\irobot-icon.png: -64.71% smaller, saved 6.82kB
2024-12-20T04:25:49.087Z INFO  spritter > .\graphics\steam-condenser\adsorber-east-shadow.png: -39.09% smaller, saved 5.19kB
2024-12-20T04:25:49.673Z INFO  spritter > .\graphics\steam-condenser\adsorber-east.png: -73.82% smaller, saved 101.05kB
2024-12-20T04:25:50.048Z INFO  spritter > .\graphics\steam-condenser\adsorber-north-shadow.png: -39.15% smaller, saved 5.11kB
2024-12-20T04:25:50.594Z INFO  spritter > .\graphics\steam-condenser\adsorber-north.png: -70.16% smaller, saved 88.25kB
2024-12-20T04:25:51.004Z INFO  spritter > .\graphics\steam-condenser\adsorber-south-shadow.png: -40.13% smaller, saved 5.96kB
2024-12-20T04:25:51.687Z INFO  spritter > .\graphics\steam-condenser\adsorber-south.png: -72.07% smaller, saved 107.68kB
2024-12-20T04:25:52.135Z INFO  spritter > .\graphics\steam-condenser\adsorber-west-shadow.png: -39.69% smaller, saved 5.76kB
2024-12-20T04:25:52.734Z INFO  spritter > .\graphics\steam-condenser\adsorber-west.png: -74.57% smaller, saved 106.66kB
2024-12-20T04:25:52.953Z INFO  spritter > .\graphics\technology\arc-furnace.png: -72.94% smaller, saved 93.42kB
2024-12-20T04:25:53.152Z INFO  spritter > .\graphics\technology\core-extractor.png: -72.14% smaller, saved 134.29kB
2024-12-20T04:25:53.336Z INFO  spritter > .\graphics\technology\low-gravity-assembling-machine.png: -70.39% smaller, saved 102.49kB
2024-12-20T04:25:53.489Z INFO  spritter > .\graphics\technology\luna.png: -51.93% smaller, saved 35.50kB
2024-12-20T04:25:53.747Z INFO  spritter > .\graphics\technology\mass-driver.png: -77.39% smaller, saved 110.13kB
2024-12-20T04:25:54.098Z INFO  spritter > .\graphics\technology\matter-cube.png: -8.95% smaller, saved 3.39kB
2024-12-20T04:25:54.164Z INFO  spritter > .\graphics\technology\neodym-refining.png: -82.69% smaller, saved 29.40kB
2024-12-20T04:25:54.374Z INFO  spritter > .\graphics\technology\polariton.png: -74.04% smaller, saved 95.69kB
2024-12-20T04:25:54.786Z INFO  spritter > .\graphics\technology\quantum-module.png: -74.55% smaller, saved 85.04kB
2024-12-20T04:25:55.233Z INFO  spritter > .\graphics\technology\quantum-science-pack.png: -74.23% smaller, saved 57.66kB
2024-12-20T04:25:55.609Z INFO  spritter > .\graphics\technology\rocket-control-unit.png: -71.65% smaller, saved 68.57kB
2024-12-20T04:25:55.682Z INFO  spritter > .\graphics\technology\rtg.png: -79.06% smaller, saved 24.31kB
2024-12-20T04:25:56.025Z INFO  spritter > .\graphics\technology\silicon-processing.png: -73.68% smaller, saved 114.28kB
2024-12-20T04:25:56.449Z INFO  spritter > .\graphics\technology\space-science-pack.png: -73.71% smaller, saved 55.62kB
2024-12-20T04:25:56.706Z INFO  spritter > .\graphics\technology\steam-condenser.png: -77.50% smaller, saved 69.81kB
2024-12-20T04:26:06.058Z INFO  spritter > .\graphics\entities\arc-furnace\arc-furnace-animation-emission-1.png: -5.44% smaller, saved 79.90kB
2024-12-20T04:26:06.445Z INFO  spritter > .\graphics\entities\arc-furnace\arc-furnace-heatpipes.png: -14.98% smaller, saved 2.14kB
2024-12-20T04:26:07.402Z INFO  spritter > .\graphics\entities\arc-furnace\arc-furnace-shadow.png: -18.68% smaller, saved 7.45kB
2024-12-20T04:26:07.627Z INFO  spritter > .\graphics\entities\arc-furnace\arc-furnace-structure.png: -12.74% smaller, saved 8.89kB
2024-12-20T04:27:02.086Z INFO  spritter > .\graphics\entities\core-extractor\core-extractor-animation-1.png: -5.71% smaller, saved 915.68kB
2024-12-20T04:27:42.964Z INFO  spritter > .\graphics\entities\core-extractor\core-extractor-animation-2.png: -5.73% smaller, saved 799.05kB
2024-12-20T04:28:32.101Z INFO  spritter > .\graphics\entities\core-extractor\core-extractor-animation-emission-1.png: -11.77% smaller, saved 823.96kB
2024-12-20T04:29:11.395Z INFO  spritter > .\graphics\entities\core-extractor\core-extractor-animation-emission-2.png: -12.00% smaller, saved 791.57kB
2024-12-20T04:29:17.006Z INFO  spritter > .\graphics\entities\core-extractor\core-extractor-shadow.png: -17.28% smaller, saved 28.42kB
2024-12-20T04:29:28.777Z INFO  spritter > .\graphics\entities\low-gravity-assembling-machine\low-gravity-assembling-machine-animation-1.png: -3.98% smaller, saved 157.88kB
2024-12-20T04:29:35.265Z INFO  spritter > .\graphics\entities\low-gravity-assembling-machine\low-gravity-assembling-machine-animation-2.png: -3.95% smaller, saved 88.46kB
2024-12-20T04:29:54.676Z INFO  spritter > .\graphics\entities\low-gravity-assembling-machine\low-gravity-assembling-machine-animation-emission-1.png: -5.38% smaller, saved 92.98kB
2024-12-20T04:30:05.642Z INFO  spritter > .\graphics\entities\low-gravity-assembling-machine\low-gravity-assembling-machine-animation-emission-2.png: -9.07% smaller, saved 92.24kB
2024-12-20T04:30:06.233Z INFO  spritter > .\graphics\entities\low-gravity-assembling-machine\low-gravity-assembling-machine-shadow.png: -22.35% smaller, saved 5.36kB
2024-12-20T04:30:06.270Z INFO  spritter > .\graphics\icons\polariton\polariton-down.png: -64.88% smaller, saved 6.24kB
2024-12-20T04:30:06.308Z INFO  spritter > .\graphics\icons\polariton\polariton-left.png: -64.75% smaller, saved 6.22kB
2024-12-20T04:30:06.342Z INFO  spritter > .\graphics\icons\polariton\polariton-right.png: -65.12% smaller, saved 6.25kB
2024-12-20T04:30:06.376Z INFO  spritter > .\graphics\icons\polariton\polariton-up.png: -64.65% smaller, saved 6.15kB
2024-12-20T04:30:06.413Z INFO  spritter > .\graphics\icons\polariton\polariton.png: -65.25% smaller, saved 6.90kB
2024-12-20T04:30:06.433Z INFO  spritter > .\graphics\item\raw-imersite\raw-imersite-1-light.png: could not optimize further
2024-12-20T04:30:06.459Z INFO  spritter > .\graphics\item\raw-imersite\raw-imersite-1.png: could not optimize further
2024-12-20T04:30:06.482Z INFO  spritter > .\graphics\item\raw-imersite\raw-imersite-2-light.png: could not optimize further
2024-12-20T04:30:06.506Z INFO  spritter > .\graphics\item\raw-imersite\raw-imersite-2.png: could not optimize further
2024-12-20T04:30:06.531Z INFO  spritter > .\graphics\item\raw-imersite\raw-imersite-3-light.png: could not optimize further
2024-12-20T04:30:06.557Z INFO  spritter > .\graphics\item\raw-imersite\raw-imersite-3.png: could not optimize further
2024-12-20T04:30:06.587Z INFO  spritter > .\graphics\item\raw-imersite\raw-imersite-light.png: -2.18% smaller, saved 76B
2024-12-20T04:30:06.611Z INFO  spritter > .\graphics\item\raw-imersite\raw-imersite.png: could not optimize further
2024-12-20T04:30:10.070Z INFO  spritter > .\graphics\resources\imersite\imersite-rift-glow.png: could not optimize further
2024-12-20T04:30:12.889Z INFO  spritter > .\graphics\resources\imersite\imersite-rift.png: -0.02% smaller, saved 149B
2024-12-20T04:30:12.890Z INFO  spritter > total: -25.56%, saved 19.99MB
```

### CODE REVIEW

**Comment by tburrows13** [comment]
Awesome! I’d been meaning to do this for a while? This also means that the rich moon rock entity graphic (from Galdoc’s Manufacturing) has been converted from 16-bit to 8-bit so I can enable its use again (16-bit graphics can’t be loaded on debug builds which is what I was developing on at the time).

Would you mind reverting the changes to the 3 Hurricane entities please? I’ve already used pngquant on them, so I’d prefer to redo compression on them from the originals at some point instead. The lossy compression that I already used isn’t great because you get a lot of visual noise as the animation plays. I seem to remember from discord discussions a few weeks again that it might be possible to get it to use the same compression quantisation across multiple frames/files, which might help?
Also the core extractor emission spritesheet has since been updated/fixed by Hurricane, so that one needs completely replacing. (It fixes the sparks in the machine near the top not being in the light layer).

**Comment by notnotmelon** [comment]
I believe the lossy compression used by spritter only compresses color channels. I could not notice any artifacting, even on animated entities.

**Comment by tburrows13** [comment]
Well the artifacting is already there because I’ve already applied the compression to those 3. It is most visible on the static parts of the low gravity assembling machine.

**Comment by notnotmelon** [comment]
I am closing this PR in order to avoid changes to the 3 hurricane entities in the git history. A new PR without such changes will be created shortly.

**Comment by tburrows13** [comment]
Oh you can just revert the changes in this PR and it’ll all work out when I squash and merge. Or revert them and `git commit —amend` then `git push -f`

**Comment by notnotmelon** [comment]
Thanks! I didn't know about `git amend`

**Comment by tburrows13** [comment]
When you `git commit --amend`, you should keep the commit message the same as the previous since the message you put there describes the whole commit, not just the amendment. (Don't worry about here, once again I will sort it in the squash-and-merge).

Also there's a merge conflict with the new icons, so do `git merge master` (or `git rebase master` and `git push -f`)

**Comment by tburrows13** [comment]
Oh I guess I shouldn’t have suggested merging in master… since this is on factorio-2.0.
Nvm, I’ll merge factorio-2.0 into master tonight and then I can update the PRs targets and merge.

**Comment by notnotmelon** [comment]
Thanks for the suggestions. I've rebased onto factorio-2.0 and optimized those 2 icons aswell.

**Pull request merged**
