### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Fr-Dae**
improve readme
link to https://github.com/tburrows13/LunarLandings/issues/15

### CODE REVIEW

**Comment by Fr-Dae** [comment]
issue and PR done, ready for merge, have a good day

**Comment by tburrows13** [comment]
Sorry, I don't see this as an improvement. Much of it needs rewriting in 2.0 anyway as it will become out-of-date (and I'll try and add some more pics/videos to break up the text too).

**Comment by Fr-Dae** [comment]
why close before i can reply ?

- i have improve chapter with the "#"
- i have add some return break , because md dont like return lign without spaces.
- i have make the "thanks you" at a list to have a better sett and better look

you don't look the "files changed" button on top ?

**Comment by Fr-Dae** [comment]
also, why do you close issue , it's link to a PR 
it's the way how github ask to do, 
- issue => branch > commit > PR with comment > merge (autoclose issue and auto delet branch)
- it's make clean and easy to review and follow and unlock auto-release update in release tab section

**[edit]** ok my bad it's a PR and not the issue you have close forget it

**Comment by tburrows13** [comment]
> issue => branch > commit > PR with comment > merge (autoclose issue and auto delet branch)

Yes this workflow is fine, if you are going to put detail of the problem in the issue, maybe have some discussion about proper solutions, and then you or someone else comes along and makes a PR to address it. If you make a completely empty issue, and then immediately make a PR that solves it (also without any explanation...) then that is just worthless noise.

> you don't look the "files changed" button on top ?

I did, and I didn't like most of the changes I saw, and it isn't worth my time to detail exactly how I want it done, when I could just do it myself (or I could just do nothing, because I mostly like it how it is. Or I could just do nothing, because I know I'll be restructuring most of it very soon anyway).

> i have add some return break , because md dont like return lign without spaces.

This is the only useful change, and even then it is only 'wrong' in the original on line 7 (where it doesn't really matter) and the Attributions section (where indeed it does look very bad on GitHub). However, even then, the readme is written for use on the mod portal itself (https://mods.factorio.com/mod/LunarLandings), it is only here so that I can keep track of it in git, and so that the github repo isn't completely empty of information. On the mod portal, text with only one newline does indeed render a newline, so the Attributions section looks fine. If I add extra newlines to make it look nice on GitHub, then it will look worse on the mod portal. Adding bullet points instead would be _ok_ but I don't think the extra visual noise improves the look either. And by adding the bullet points, you also messed up the 4 lines of "Kevin MacLeod" attribution, which shouldn't be on separate bullet points.

**Pull request closed without merging**
